import type { Metadata } from "next";
import { Agdasima } from "next/font/google";
import "./globals.css";
import Header  from "./components/header";
const geistSans = Agdasima({
  variable: "--font-geist-sans",
  subsets: ["latin"],
  weight:"400"
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.className}  antialiased`}
      >
        <h2 className="text-3xl">suki</h2>
        <Header></Header>
        {children}
      </body>
    </html>
  );
}
